### ISSUE TITLE
"Command Part is unknown" error when calling Java methods using large byte arrays

### ISSUE THREAD

**Issue by JoshRosen** [py4j/py4j#109]
It looks like calls to methods that accept byte arrays may fail depending on the size of the arrays.  For example:

``` python
from py4j.java_gateway import java_import, JavaGateway                          
gateway = JavaGateway.launch_gateway(die_on_exit=True)                          
# This call works:                                                              
gateway.jvm.java.nio.ByteBuffer.wrap(bytearray(255 for _ in range(10)))         
# This call fails:                                                              
gateway.jvm.java.nio.ByteBuffer.wrap(bytearray(255 for _ in range(100)))
```

The second call fails with this error:

```
py4j.protocol.Py4JError: An error occurred while calling z:java.nio.ByteBuffer.wrap. Trace:
py4j.Py4JException: Command Part is unknown: /////////////////////////////////////////////////////////w==
    at py4j.Protocol.getObject(Protocol.java:290)
    at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:81)
    at py4j.commands.CallCommand.execute(CallCommand.java:77)
    at py4j.GatewayConnection.run(GatewayConnection.java:207)
    at java.lang.Thread.run(Thread.java:680)
```

The issue seems to be related to the size of the arrays.  I turned on debug logging and it looks like this might have something to do with how the byte array data is split across multiple lines in the text protocol.

**Comment by dhwajraj** [comment]
This issue reappears in 0.10.3 
works fine when I downgraded to 0.9

**Comment by bartdag** [comment]
Hi @dhwajraj, does it fail with the code submitted by Josh at the top of the issue? When I try it with 0.10.3, I don't receive any error.

**Comment by dhwajraj** [comment]
Hi @bartdag.yes the command error is different. I am getting "yro4" with 0.10.3

**Comment by bartdag** [comment]
Can you open a new issue with some code examples to replicate? yr04 is a response formatted using Py4J text protocol so you should never see it. Also, make sure that both the Java and Python sides are using the same version of Py4J: the protocol significantly changed between 0.9 and 0.10.x.

**Comment by xinyicheng** [comment]
Hi @bartdag ,When I try it with 0.10.6,it fails with this error:
`py4j.protocol.Py4JJavaError: An error occurred while calling o22.awaitTermination.
: py4j.Py4JException: Command Part is unknown: yro52
	at py4j.Protocol.getObject(Protocol.java:307)
	at py4j.Protocol.getReturnValue(Protocol.java:438)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy15.call(Unknown Source)`
How to fix the issue?thank you.
