### ISSUE TITLE
Support nan/inf between Python and Java

### ISSUE THREAD

**Issue by davies** [py4j/py4j#152]
The nan and infilite value of float is serialized different in Python and Java:

In Python, they are 

```
nan, inf, -inf
```

In Java, they are

```
NaN, Infinity, +Infinity, -Infinity
```

**Comment by nvyin** [comment]
Hi, I have an issue  with Double.POSITIVE_INFINITY, 

can we assign  double F[20] = Double.POSITIVE_INFINITY, 

???

**Comment by bartdag** [comment]
@nvyin I do not understand your question, can you provide more context/code? Is this related to Py4J?
