### ISSUE TITLE
Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)

### ISSUE THREAD

**Issue by itsvks** [py4j/py4j#321]
I am using below mentioned version

**Python**  : 3.6.5
**Java** : 
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

And running commands which is given in doc 

from py4j.java_gateway import JavaGateway
gateway = JavaGateway()
random = gateway.jvm.java.util.Random()

After 3rd line I am getting error : **Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)**

Please help.

**Comment by bartdag** [comment]
Did you start the GatewayServer in a JVM before running the Python code? Alternatively you can use the launch_gateway function (https://www.py4j.org/py4j_java_gateway.html#py4j.java_gateway.launch_gateway and https://www.py4j.org/advanced_topics.html#using-py4j-without-pre-determined-ports-dynamic-port-number)

**Comment by mprogram** [comment]
As a side note to suggest here, @bartdag: could you, please, update the docs with a better step-by-step demo instructions? Indeed, one would try first running the python code afore starting the GatewayServer in a JVM for a simple reason the text pointing to the Java code (see the [Py4J homepage](https://www.py4j.org/) from which the following snippet was taken with my emphasis added):
> _Note that the Java program must be started **before** executing the Python code above. . In other words, the Py4J does not start a JVM._.

(without saying how in easy reproducible steps for a curious web surfing passer-by) happens to be a little non-coherent as one has to jump back (and now how) to continue with the example, and, perhaps, indeed, start a JMV with the Py4J as you've suggested in your previous comment? Many thanks for developing Py4J.

**Comment by tanaponlee** [comment]
I am also new to py4j as well. I followed section 3.6 Using Py4J without pre-determined ports from this link: https://www.py4j.org/advanced_topics.html and it works for me.

from py4j.java_gateway import *
port = launch_gateway()
gateway = JavaGateway(
    gateway_parameters=GatewayParameters(port=port),
    callback_server_parameters=CallbackServerParameters(port=0))
random = gateway.jvm.java.util.Random()


FYI
Python 3.5.6
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by Andy2018f** [comment]
I solved the problem changing the python path that i used with spyder/anconda to Continuum\\anaconda3
Basically you need to check if you have py4j in your share file in python.
Good luck
