### ISSUE TITLE
Certain method names don't get imported

### ISSUE THREAD

**Issue by nirav2** [py4j/py4j#409]
I have a Scala method 'isValid(token: String): String' in a class with several methods. For some reason Py4J doesn't like the name of this method and drops it on the floor. Resulting in: 'isValid does not exist in the JVM'. If I change the method name to 'isValidToken(token: String): String' it goes through. Same for 'getAkvSecret' and 'putAkvSecret'. It works if I change the method names to 'getSecret' and 'putSecret'. Wonder what could be causing this? Py4J version: 0.10.7 being brought in by Spark 2.4.

**Comment by HyukjinKwon** [comment]
@nirav2 I am 99% sure that your method has a different name on JVM, e.g., with $. Scala compiler creates a different class name in class files.  It would be easier to investigate it further if you provide your codes or example.

**Comment by HyukjinKwon** [comment]
I am closing for now as there's no actionable item per the current description
