### ISSUE TITLE
Py4J is supported with Python 3.8 and 3.9

### ISSUE THREAD

**Issue by larajorge11** [py4j/py4j#437]
Hi, looking the documentation (Readme, py4j documentation, PyPI) there is just information that py4j was tested until python 3.7 so far, I am wondering if the documentation is not updated yet or py4j is not recommended for the new versions of python. I already did some test consuming Java objects like a Map and List using 3.8 and 3.9 and works well.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/py4j/py4j/pull/443
