### ISSUE TITLE
java如何调用py文件中的指定的函数，而不是使用interface实现机制

### ISSUE THREAD

**Issue by w757227129** [py4j/py4j#458]
我有一个hello.py文件，里面仅仅只有一个函数,如下
def execute():
    print("Method is called by Java side")

我如何通过py4j调用指定的(execute)函数

**Comment by HyukjinKwon** [comment]
@w757227129, I would appreciate that if you file a JIRA in English. Many of maintainers here don't speak other languages much. Let me close it for now for visibility. Feel free to reopen after editing the issue 👍
