### ISSUE TITLE
Build failure in python 3.10. Any plan supporting 3.10 soon?

### ISSUE THREAD

**Issue by sayanchk** [py4j/py4j#476]
Hi all,
We have an indirect dependency to py4j through another package and the latest 0.10.9.4 release is failing with the following error:
```
from py4j.clientserver import ClientServer
/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/py4j/clientserver.py:12: in <module>
    from collections import deque, Callable
E   ImportError: cannot import name 'Callable' from 'collections' (/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/collections/__init__.py)
```

The build was working fine under 0.10.9.3 in python 3.10. Any plan to support python 3.10 soon?

**Comment by HyukjinKwon** [comment]
Will add the CI, make a fix, and crewte another maintaunence release shortly
