### ISSUE TITLE
Migrate from nosetests to PyTests

### ISSUE THREAD

**Issue by HyukjinKwon** [py4j/py4j#478]
`nose` is no longer maintained, and it doesn't, for example, support Python 3.10. See also https://github.com/py4j/py4j/pull/477/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R59-R61

**Comment by HyukjinKwon** [comment]
@itholic mind taking a look when you find some time?

**Comment by bartdag** [comment]
As mentioned in another pull request, we will need to use pytest 4.6.9 when testing with python 2.7 and 3.4. We can use a more recent version when testing with newer python versions.

Unless we use exotic pytest features, just depending on pytest should be enough. It is quite backward compatible in my experience.
