### ISSUE TITLE
[Help] License For Redistribution

### ISSUE THREAD

**Issue by casionone** [py4j/py4j#483]
We used the py4j-python[1] module code in the project source code in the form of a zip file[2].
I have two questions to ask:

1. We have noticed,old version 0.10.7,The header of backport.py[3] states:
"Backported functions from later versions of python (mostly 2.7) These functions are all licensed under the PSF License." But According to CONTRIBUTING.rst[4],"Py4J does not have an official Contributor License Agreement (CLA), but it is assumed that as soon as you make a contribution (patch, code suggestion through any medium, pull requests) to Py4J, you accept that your code will be redistributed under the current license used by Py4J, i.e., the new BSD license. This is an irrevocable right to ensure that developers can use Py4J without the fear of seeing parts removed in the future."
so backport.py are licensed under the new BSD License?

2. We redistributed the py4j-python[1] module as a zip[1]. We have added the license description of py4j[5] and the license file[6] in the projecct source code, but not in the zip file[1], does this compound py4j's source code redistribution requirements?

[1]https://github.com/py4j/py4j/tree/master/py4j-python
[2]https://github.com/apache/incubator-linkis/blob/dev-1.1.1/linkis-engineconn-plugins/engineconn-plugins/python/src/main/py4j/py4j-0.10.9.5-src.zip
[3]https://github.com/py4j/py4j/blob/0.10.7/py4j-python/src/py4j/backport.py
[4]https://github.com/py4j/py4j/blob/master/CONTRIBUTING.rst
[5]https://github.com/apache/incubator-linkis/blob/dev-1.1.1/LICENSE
[6]https://github.com/apache/incubator-linkis/blob/dev-1.1.1/licenses/LICENSE-py4j-0.10.9.5-src.txt

**Comment by HyukjinKwon** [comment]
I think we should drop Python 2.6 and remove `backport.py` away. I even think about removing all Python 2 out since Python 2 reached EOL but would better be conservative.

**Comment by HyukjinKwon** [comment]
Actually, that's not referenced anymore after https://github.com/py4j/py4j/commit/ac9e0e26911954a26df0884b10cd63e9b4a46e1c. Let'e remove that away.

**Comment by HyukjinKwon** [comment]
Okay, it was removed in https://github.com/py4j/py4j/commit/ac9e0e26911954a26df0884b10cd63e9b4a46e1c, and it's only the problem in old releases, is that right?

**Comment by HyukjinKwon** [comment]
There's nothing we can do on the released artifacts. The only way would be to use the latest version.

**Comment by HyukjinKwon** [comment]
> so backport.py are licensed under the new BSD License?

That's correct IIRC. However, you might need to cross-check the license specifications.

**Comment by casionone** [comment]
> > so backport.py are licensed under the new BSD License?
> 
> That's correct IIRC. However, you might need to cross-check the license specifications.

Thanks,  
for Q2 about redistributed, the license file[6] in the projecct source code, but not in the zip file[1], it is ok?
