### ISSUE TITLE
enable_auth has some error in windows

### ISSUE THREAD

**Issue by kun1996** [py4j/py4j#484]
py4j/py4j-python/src/py4j/java_gateway.py   line 341-342
` 
if enable_auth:
     _auth_token = proc.stdout.readline()[:-1]
`
In windows, if enable_auth is true, stdout.readline() will end with \r\n
_auth_token will error, maybe can use rstrip()

**Comment by kun1996** [comment]
`
from py4j.java_gateway import JavaGateway

gateway = JavaGateway.launch_gateway(enable_auth=True)
random = gateway.jvm.java.util.Random()
`

This is test code in windows, I find  that CI only tested ubuntu, I don't know if there are plans to support Windows

**Comment by HyukjinKwon** [comment]
The auth token might have newline characters so we should do something like `len(os.linesep)` instead of `-1`.

We should probably setup a CI with Windows too e.g., AppVeyor.

**Comment by HyukjinKwon** [comment]
Or Github Actions e.g., https://blog.devgenius.io/write-your-github-actions-workflow-for-build-windows-application-94e5a989f477

**Comment by HyukjinKwon** [comment]
@kun1996 are you interested in trying to set Windows CI up? that would be super great improvement in Py4J project ..
