### ISSUE TITLE
(eclipse.)py4j.org disappeared thus breaking builds

### ISSUE THREAD

**Issue by marco-miller** [py4j/py4j#527]
Since early yesterday it seems,
- [py4j.org](http://py4j.org/) (thus [eclipse.py4j.org](http://eclipse.py4j.org/)) became unreachable entirely.
- Among potentially others, this breaks the Trace Compass Incubator build [1,2].
- How can this be remedied? (Thanks for any help you may provide.)

[1] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3447#steps-to-reproduce
[2] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3447#what-is-the-current-bug-behavior

**Comment by bartdag** [comment]
@marco-miller this should be resolved now. i'll provide more info now (running between meetings now)

**Comment by bartdag** [comment]
This was a very basic issue with the domain registrar (the automated domain renewal failed and I missed the notification). It is now resolved.

**Comment by marco-miller** [comment]
> This was a very basic issue with the domain registrar (the automated domain renewal failed and I missed the notification). It is now resolved.

Alright; thanks again for the fix!
